RK3 + RK4
frontend-park-mail-ru/2017_2_ToP pull request #188
Opened 2017-12-14 17:34 UTC by pryahin

2017-12-14 18:37 UTC, vladpereskokov commented
Уберите тонну css в font-awesome

2017-12-15 08:55 UTC, v-pereskokov requested changes

2017-12-15 08:55 UTC, v-pereskokov commented on src/modules/MultiEvents/MultiEvents.js
> +    EventTarget.prototype.addMultiEvents = function addMultiEvents(events, handler) {
А как же стрелочные функции?

2017-12-15 08:55 UTC, v-pereskokov commented on src/ServiceWorker.js
> +    // console.log(event);
От такого избавиться

2017-12-15 08:55 UTC, v-pereskokov commented on src/ServiceWorker.js
> +    // console.log(event);
Везде

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Form/Form.js
>                      console.log(`login: ${response.login}\nemail: ${response.email}`);
Такого в проде не должно быть

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Form/Form.js
> +                .catch(async response => {
А почему все не через `async/await`?

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Game/Stages/Listening/Listening.js
>          super('div', {'class': 'listening-stage'}, data);
Не обязательно писать `'class', можно просто class`

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Header/Header.scss
> +@import "../../static/css/_config.scss";
Вы юзайте один стиль. Либо везде ", либо везде '

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Menu/Menu.js
>                      .then(() => {
Мб async?

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Game/Stages/PreGame/PreGame.js
> +
Копипаста из функции выше

2017-12-15 08:55 UTC, v-pereskokov commented on src/components/Menu/Menu.scss
> +    //width: 290px;
Выкинуть

2017-12-15 08:55 UTC, vladpereskokov commented on src/game/GameManager/GameManager.js
> +        if (this.strategy) {
Тернарные операторы в таких случаях же лучше смотрятся, нет?

2017-12-15 08:55 UTC, vladpereskokov commented on src/game/Strategy/Multiplayer/MultiPlayerStrategy.js
> +            const result = {
Можно и сразу в send засунуть

2017-12-15 08:55 UTC, vladpereskokov commented on src/game/Strategy/Singleplayer/SinglePlayerStrategy.js
> +            if (event.code === 1006) {
А почему не 2007? Что за магия

2017-12-15 08:55 UTC, vladpereskokov commented on src/modules/CreateTopRouter/CreateTopRouter.js
>      UserService.getData()
Странно, что не везде поменяли на `async`

2017-12-15 11:41 UTC, pryahin commented on src/modules/MultiEvents/MultiEvents.js
> +    EventTarget.prototype.addMultiEvents = function addMultiEvents(events, handler) {
Тут нельзя со стрелочной

2017-12-15 14:37 UTC, vladpereskokov commented on src/modules/MultiEvents/MultiEvents.js
> +    EventTarget.prototype.addMultiEvents = function addMultiEvents(events, handler) {
Ок, принято

2017-12-15 15:45 UTC, v-pereskokov approved these changes

2017-12-15 15:50 UTC, merged